language: elixir

elixir:
  - 1.8.1

addons:
  postgresql: '11.2'

services:
  - postgresql

before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11

before_script:
  - psql --version
  - cp config/travis.exs config/test.exs
  - cp config/travis.exs config/dev.exs
  - mix do ecto.create, ecto.migrate

script:
  - mix test
