language: elixir

elixir:
  - 1.8.1

addons:
  postgresql: '9.6'

services:
  - postgresql

before_script:
  - psql --version
  - cp config/travis.exs config/test.exs
  - rm config/dev.exs
  - cp config/travis.exs config/dev.exs
  - mix do ecto.create, ecto.migrate

script:
  - mix test
