language: elixir

elixir:
  - 1.8.1

addons:
  postgresql: '11.2'

services:
  - postgresql

before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate

script:
  - mix test
  